services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: always
    networks:
      - searxng-network
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - BASE_URL=https://pedro.local/
      - INSTANCE_NAME=SearXNG Local
      - SEARXNG_SECRET=pedro
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  redis:
      image: redis:7-alpine
      container_name: redis
      restart: always
      networks:
        - searxng-network
      volumes:
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        - redis-data:/data
      command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: always
    networks:
      - searxng-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - searxng

networks:
  searxng-network:
    driver: bridge

volumes:
  redis-data:
  caddy-data:
  caddy-config:
